dist: trusty

language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libssl1.0.0

before_install:
    - pip install --user cpp-coveralls

compiler:
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=On -DTRAVIS=On

script:
    - make
    - ctest -V

after_success:
    - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*" -E ".*test_main/.*.cpp.*" -E ".*test_main/.*.h.*" -E ".*test_main/.*.cc.*"
